package(default_visibility = ["//visibility:public"])

java_binary(
    name = "main",
    srcs = glob(["**/*.java"]),
    main_class = "Main",
    deps = [
        "//3rdpartydeps:com_github_davidmoten_rxjava_extras",
        "//3rdpartydeps:com_github_davidmoten_rxjava_jdbc",
        "//3rdpartydeps:com_sparkjava_spark_core",
        "//3rdpartydeps:commons_io_commons_io",
        "//3rdpartydeps:io_reactivex_rxjava",
        "//3rdpartydeps:io_reactivex_rxjava2_rxjava",
        "//3rdpartydeps:io_reactivex_rxjava_math",
        "//3rdpartydeps:io_reactivex_rxjava_string",
        "//3rdpartydeps:javax_servlet_javax_servlet_api",
        "//3rdpartydeps:org_eclipse_jetty_jetty_http",
        "//3rdpartydeps:org_eclipse_jetty_jetty_io",
        "//3rdpartydeps:org_eclipse_jetty_jetty_security",
        "//3rdpartydeps:org_eclipse_jetty_jetty_server",
        "//3rdpartydeps:org_eclipse_jetty_jetty_servlet",
        "//3rdpartydeps:org_eclipse_jetty_jetty_util",
        "//3rdpartydeps:org_eclipse_jetty_jetty_webapp",
        "//3rdpartydeps:org_eclipse_jetty_jetty_xml",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_api",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_client",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_common",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_server",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_servlet",
        "//3rdpartydeps:org_postgresql_postgresql",
        "//3rdpartydeps:org_reactivestreams_reactive_streams",
        "//3rdpartydeps:org_slf4j_slf4j_api",
        "//3rdpartydeps:org_slf4j_slf4j_simple",
    ],
)

java_library(
    name = "lib",
    srcs = glob(
        ["**/*.java"],
        exclude = ["Main.java"],
    ),
    deps = [
        "//3rdpartydeps:com_github_davidmoten_rxjava_extras",
        "//3rdpartydeps:com_github_davidmoten_rxjava_jdbc",
        "//3rdpartydeps:com_sparkjava_spark_core",
        "//3rdpartydeps:commons_io_commons_io",
        "//3rdpartydeps:io_reactivex_rxjava",
        "//3rdpartydeps:io_reactivex_rxjava2_rxjava",
        "//3rdpartydeps:io_reactivex_rxjava_math",
        "//3rdpartydeps:io_reactivex_rxjava_string",
        "//3rdpartydeps:javax_servlet_javax_servlet_api",
        "//3rdpartydeps:org_eclipse_jetty_jetty_http",
        "//3rdpartydeps:org_eclipse_jetty_jetty_io",
        "//3rdpartydeps:org_eclipse_jetty_jetty_security",
        "//3rdpartydeps:org_eclipse_jetty_jetty_server",
        "//3rdpartydeps:org_eclipse_jetty_jetty_servlet",
        "//3rdpartydeps:org_eclipse_jetty_jetty_util",
        "//3rdpartydeps:org_eclipse_jetty_jetty_webapp",
        "//3rdpartydeps:org_eclipse_jetty_jetty_xml",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_api",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_client",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_common",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_server",
        "//3rdpartydeps:org_eclipse_jetty_websocket_websocket_servlet",
        "//3rdpartydeps:org_postgresql_postgresql",
        "//3rdpartydeps:org_reactivestreams_reactive_streams",
        "//3rdpartydeps:org_slf4j_slf4j_api",
        "//3rdpartydeps:org_slf4j_slf4j_simple",
    ],
)
