package(default_visibility = ["//visibility:public"])

java_library(
    name = "org_eclipse_jetty_websocket_websocket_common",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_websocket_websocket_api//jar",
        "@org_eclipse_jetty_websocket_websocket_common//jar",
    ],
)

java_library(
    name = "commons_io_commons_io",
    visibility = ["//visibility:public"],
    exports = [
        "@commons_io_commons_io//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_server",
    visibility = ["//visibility:public"],
    exports = [
        "@javax_servlet_javax_servlet_api//jar",
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_server//jar",
        "@org_eclipse_jetty_jetty_util//jar",
    ],
)

java_library(
    name = "org_reactivestreams_reactive_streams",
    visibility = ["//visibility:public"],
    exports = [
        "@org_reactivestreams_reactive_streams//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_io",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_util//jar",
    ],
)

java_library(
    name = "io_reactivex_rxjava_string",
    visibility = ["//visibility:public"],
    exports = [
        "@io_reactivex_rxjava_string//jar",
    ],
)

java_library(
    name = "com_sparkjava_spark_core",
    visibility = ["//visibility:public"],
    exports = [
        "@com_sparkjava_spark_core//jar",
        "@javax_servlet_javax_servlet_api//jar",
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_security//jar",
        "@org_eclipse_jetty_jetty_server//jar",
        "@org_eclipse_jetty_jetty_servlet//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_jetty_webapp//jar",
        "@org_eclipse_jetty_jetty_xml//jar",
        "@org_eclipse_jetty_websocket_websocket_api//jar",
        "@org_eclipse_jetty_websocket_websocket_client//jar",
        "@org_eclipse_jetty_websocket_websocket_common//jar",
        "@org_eclipse_jetty_websocket_websocket_server//jar",
        "@org_eclipse_jetty_websocket_websocket_servlet//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_websocket_websocket_servlet",
    visibility = ["//visibility:public"],
    exports = [
        "@javax_servlet_javax_servlet_api//jar",
        "@org_eclipse_jetty_websocket_websocket_api//jar",
        "@org_eclipse_jetty_websocket_websocket_servlet//jar",
    ],
)

java_library(
    name = "io_reactivex_rxjava",
    visibility = ["//visibility:public"],
    exports = [
        "@io_reactivex_rxjava//jar",
    ],
)

java_library(
    name = "org_postgresql_postgresql",
    visibility = ["//visibility:public"],
    exports = [
        "@org_postgresql_postgresql//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_websocket_websocket_api",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_websocket_websocket_api//jar",
    ],
)

java_library(
    name = "org_slf4j_slf4j_api",
    visibility = ["//visibility:public"],
    exports = [
        "@org_slf4j_slf4j_api//jar",
    ],
)

java_library(
    name = "com_github_davidmoten_rxjava_extras",
    visibility = ["//visibility:public"],
    exports = [
        "@com_github_davidmoten_rxjava_extras//jar",
        "@io_reactivex_rxjava//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_util",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_util//jar",
    ],
)

java_library(
    name = "io_reactivex_rxjava2_rxjava",
    visibility = ["//visibility:public"],
    exports = [
        "@io_reactivex_rxjava2_rxjava//jar",
        "@org_reactivestreams_reactive_streams//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_websocket_websocket_server",
    visibility = ["//visibility:public"],
    exports = [
        "@javax_servlet_javax_servlet_api//jar",
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_servlet//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_websocket_websocket_api//jar",
        "@org_eclipse_jetty_websocket_websocket_client//jar",
        "@org_eclipse_jetty_websocket_websocket_common//jar",
        "@org_eclipse_jetty_websocket_websocket_server//jar",
        "@org_eclipse_jetty_websocket_websocket_servlet//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_servlet",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_security//jar",
        "@org_eclipse_jetty_jetty_server//jar",
        "@org_eclipse_jetty_jetty_servlet//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_websocket_websocket_client",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_websocket_websocket_client//jar",
        "@org_eclipse_jetty_websocket_websocket_common//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_http",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_util//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_security",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_security//jar",
        "@org_eclipse_jetty_jetty_server//jar",
    ],
)

java_library(
    name = "javax_servlet_javax_servlet_api",
    visibility = ["//visibility:public"],
    exports = [
        "@javax_servlet_javax_servlet_api//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_xml",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_jetty_xml//jar",
    ],
)

java_library(
    name = "io_reactivex_rxjava_math",
    visibility = ["//visibility:public"],
    exports = [
        "@io_reactivex_rxjava_math//jar",
    ],
)

java_library(
    name = "org_slf4j_slf4j_simple",
    visibility = ["//visibility:public"],
    exports = [
        "@org_slf4j_slf4j_api//jar",
        "@org_slf4j_slf4j_simple//jar",
    ],
)

java_library(
    name = "com_github_davidmoten_rxjava_jdbc",
    visibility = ["//visibility:public"],
    exports = [
        "@com_github_davidmoten_rxjava_extras//jar",
        "@com_github_davidmoten_rxjava_jdbc//jar",
        "@commons_io_commons_io//jar",
        "@io_reactivex_rxjava//jar",
        "@io_reactivex_rxjava_math//jar",
        "@io_reactivex_rxjava_string//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)

java_library(
    name = "org_eclipse_jetty_jetty_webapp",
    visibility = ["//visibility:public"],
    exports = [
        "@org_eclipse_jetty_jetty_security//jar",
        "@org_eclipse_jetty_jetty_server//jar",
        "@org_eclipse_jetty_jetty_servlet//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_jetty_webapp//jar",
        "@org_eclipse_jetty_jetty_xml//jar",
    ],
)
